"""init

Revision ID: 892734376653
Revises: 
Create Date: 2025-05-19 23:14:14.754628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '892734376653'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('crm', sa.String(), nullable=True),
    sa.Column('especialidade', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medico_id'), 'medico', ['id'], unique=False)
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_paciente_id'), 'paciente', ['id'], unique=False)
    op.create_table('consulta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prontuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atendimento',
    sa.Column('id_atendimento', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id_prontuario', sa.Integer(), nullable=False),
    sa.Column('id_medico', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_medico'], ['medico.id'], ),
    sa.ForeignKeyConstraint(['id_prontuario'], ['prontuario.id'], ),
    sa.PrimaryKeyConstraint('id_atendimento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('atendimento')
    op.drop_table('prontuario')
    op.drop_table('consulta')
    op.drop_index(op.f('ix_paciente_id'), table_name='paciente')
    op.drop_table('paciente')
    op.drop_index(op.f('ix_medico_id'), table_name='medico')
    op.drop_table('medico')
    # ### end Alembic commands ###
